services: # コンテナの定義開始
  db: # PostgreSQLデータベースの設定
    image: postgres:13 # PostgreSQLの公式イメージを使用
    environment: # 環境変数の設定
      POSTGRES_USER: ${POSTGRES_USER:-user} # 環境変数を使用
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password} # 環境変数を使用
      POSTGRES_DB: ${POSTGRES_DB:-myapp_production} # 環境変数を使用
      TZ: Asia/Tokyo # タイムゾーンを日本
    volumes: # データの永続化設定
      - pg_data:/var/lib/postgresql/data # DBデータを永続化
    ports: # ポート設定
      - "5432:5432" # PostgreSQLのポート
    healthcheck: # コンテナの健康チェック設定
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user}"]
      interval: 10s # チェック間隔
      timeout: 10s # タイムアウト時間
      retries: 3 # リトライ回数

  web: # Railsアプリケーションの設定
    build: # Dockerイメージのビルド設定
      context: . # ビルドコンテキストはカレントディレクトリ
      dockerfile: Dockerfile.dev # 開発用Dockerfileを使用
    command: bash -c "bundle install && bundle exec rails db:prepare && rm -f tmp/pids/server.pid && ./bin/dev"
    tty: true # 擬似ターミナルを割り当て
    stdin_open: true # 標準入力を保持
    volumes: # ボリュームマウントの設定
      - .:/myapp # ソースコードのマウント
      - bundle_data:/usr/local/bundle:cached # gemの永続化
      - node_modules:/myapp/node_modules # node_modulesの永続化
    environment: # 環境変数の設定
      TZ: Asia/Tokyo # タイムゾーンを日本に設定
      DATABASE_URL: ${DATABASE_URL:-postgres://user:${POSTGRES_PASSWORD}@db/myapp_production} # PostgreSQL用の環境変数
    ports: # ポート設定
      - "3000:3000" # Rails標準のポート
    depends_on: # 依存関係の設定
      db: # dbサービスに依存
        condition: service_healthy # dbの健康チェックが通るまで待機

volumes: # ボリュームの定義
  pg_data: # PostgreSQLデータの永続化用ボリューム
  bundle_data: # gemデータの永続化用ボリューム
  node_modules: # Node.jsパッケージの永続化用ボリューム